service: sqs

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: python3.8

functions:
  group3-extract:
    handler: handler.start
    module: extract
    events:
      - sqs: !GetAtt Group3-SQS-ExtracttoTransform.Arn
      
resources:
  Resources:
    Group3-SQS-ExtracttoTransform:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "Group3-SQS-ExtracttoTransform"

# service: group-3
# plugins:
#   - serverless-python-requirements
# provider:
#   name: aws
#   stage: dev
#   region: eu-west-1

# package:
#   individually: true

# functions:
#   redshift-lambda:
#     runtime: python3.8
#     handler: handler.start
#     module: redshift_lambda
