
service: group-3

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: python3.8

package:
  individually: true
  exclude:
    - node_modules/**
    - local_*

functions:
  group3-extract:
    handler: handler.start
    module: extract
    include: 
      - extract

  group3-transform:
    handler: handler.start
    iamRoleStatements:
      - Effect: "Allow"
        Action:
        - sqs:ReceiveMessage
        Resource: !GetAtt Group3SQSExtracttoTransform.Arn
    module: transform
    include: 
      - transform
    events:
      - sqs:
          arn: !GetAtt Group3SQSExtracttoTransform.Arn

  group3-load:
    handler: handler.start
    iamRoleStatements:
      - Effect: "Allow"
        Action: 
        - sqs: SendMessage
        Resource: !GetAtt Group3SQSTransormtoLoad.Arn
    module: load
    include: 
      - load
    events:
      - sqs:
          arn: !GetAtt Group3SQSTransormtoLoad.Arn

  redshift-lambda:
    runtime: python3.8
    handler: handler.start
    module: redshift_lambda


resources:
  Resources:
    Group3SQSExtracttoTransform:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "Group3SQSExtracttoTransform"

plugins:
  - serverless-python-requirements
