
service: group-3-test

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: python3.8
  # iamRoleStatements:
  # - Effect: Allow
  #   Action:
  #   - sqs:SendMessage
  #   - s3:Get*
  #   - s3:List*
  #   Resource: !GetAtt group-3-extract.Arn
  #   # Resource: arn:aws:lambda:eu-west-1:579154747729:function:group-3-dev-group3-extract
  # - Effect: Allow
  #   Action:
  #   - sqs:ReceiveMessage
  #   - sqs:DeleteMessage
  #   - sqs:SendMessage
  #   Resource: !GetAtt group-3-transform.Arn
  #   # Resource: arn:aws:lambda:eu-west-1:579154747729:function:group-3-dev-group3-transform
  # - Effect: Allow
  #   Action: 
  #   - sqs:ReceiveMessage
  #   - sqs:SendMessage
  #   - redshift:*
  #   Resource: !GetAtt group-3-load.Arn
  #   # Resource: arn:aws:lambda:eu-west-1:579154747729:function:group-3-dev-group3-load
  # - Effect: Allow
  #   Action: 
  #   - lambda:CreateEventSourceMapping
  #   - lambda:ListEventSourceMappings
  #   - lambda:ListFunctions
  #   - sqs:*
  #   Resource: !GetAtt Group3SQSExtracttoTransform.Arn
  # - Effect: Allow
  #   Action: 
  #   - lambda:CreateEventSourceMapping
  #   - lambda:ListEventSourceMappings
  #   - lambda:ListFunctions
  #   - sqs:*
  #   Resource: !GetAtt Group3SQSTransformtoLoad.Arn


package:
  individually: true
  exclude:
    - node_modules/**
    - local_*

functions:
  extract:
    handler: handler.start
    module: extract
    include: 
      - extract
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: !GetAtt testGroup3SQSExtracttoTransform.Arn
      - Effect: Allow
        Action:
          - s3:Get*
          - s3:List*
        Resource:
          - arn:aws:s3:::cafe-transactions
          - arn:aws:s3:::cafe-transactions/*
      - Effect: Allow
        Action:
          - lambda:InvokeFunction
        Resource: !GetAtt group-3-test-dev-extract


  transform:
    handler: handler.start
    module: transform
    include: 
      - transform
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:ReceiveMessage
          - sqs:DeleteMessage
          - sqs:SendMessage
        Resource: !GetAtt testGroup3SQSTransformtoLoad.Arn
    events:
      - sqs:
          arn: !GetAtt testGroup3SQSExtracttoTransform.Arn

  load:
    handler: handler.start
    module: load
    include: 
      - load
      - psycopg2
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - sqs:ReceiveMessage
          - sqs:SendMessage
          - redshift:*
    events:
      - sqs:
          arn: !GetAtt testGroup3SQSTransformtoLoad.Arn
    environment:
      DB_CLUSTER: "bir1-cluster"
      DB_HOST: "10.0.1.223"
      DB_NAME: "dev"
      DB_PASS: "*y3EoPZH*Luazyc#%i^xS#jc%n5$WSY^o%PThw!U"
      DB_PORT: "5439"
      DB_USER: "awsuser"
    vpc:
      securityGroupIds:
        - sg-03601054033ee65d6
        - sg-04ffa039212cd915c
      subnetIds:
        - subnet-0b0c0f6ea99bda1ee

resources:
  Resources:
    testGroup3SQSExtracttoTransform:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "testGroup3SQSExtracttoTransform"

    testGroup3SQSTransformtoLoad:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "testGroup3SQSTransformtoLoad"
    
    EventInvokeConfig:
      Type: "AWS::Lambda::EventInvokeConfig"
      Properties:
        FunctionName: "group-3-test-dev-extract"
        #MaximumRetryAttempts: 1
        DestinationConfig:
          OnSuccess:
            Destination: !GetAtt testGroup3SQSExtracttoTransform.Arn
        Qualifier: "$LATEST"
        #MaximumEventAgeInSeconds: 600
  
  
  # group-3-dev-extract:
  #   Type: "AWS::Lambda::Function"
  #   Properties:
  #     FunctionName: "group-3-dev-extract"
  
  # group-3-dev-transform:
  #   Type: "AWS::Lambda::Function"
  #   Properties:
  #     FunctionName: "group-3-dev-transform"
  
  # group-3-dev-load:
  #   Type: "AWS::Lambda::Function"
  #   Properties: 
  #     FunctionName: "group-3-dev-load" 

plugins:
  - serverless-python-requirements
