service: group-3

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: python3.8

package:
  individually: true
  exclude:
    - node_modules/**
    - local_*

functions:
  group3-extract:
    handler: handler.start
    module: extract
    include: 
      - extract
    events:
      - sqs:
          arn: !GetAtt Group3SQSExtracttoTransform.Arn

  # group3-transform:
  # group3-load:

resources:
  Resources:
    Group3SQSExtracttoTransform:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "Group3SQSExtracttoTransform"

plugins:
  - serverless-python-requirements

# functions:
#   redshift-lambda:
#     runtime: python3.8
#     handler: handler.start
#     module: redshift_lambda
