service: sqs

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - sqs: !GetAtt Group3SQS1.Arn
      
resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "Group3SQS1"

# service: group-3
# plugins:
#   - serverless-python-requirements
# provider:
#   name: aws
#   stage: dev
#   region: eu-west-1

# package:
#   individually: true

# functions:
#   redshift-lambda:
#     runtime: python3.8
#     handler: handler.start
#     module: redshift_lambda
